# Generated by Django 2.2 on 2019-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KeepItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro_cool.Retrospective')),
            ],
        ),
        migrations.CreateModel(
            name='ImproveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro_cool.Retrospective')),
            ],
        ),
    ]
